version: '3.1'

services:
  web:
    build: .
    env_file:
      - .env
    container_name: 'shortener'
    restart: always
    ports:
      - '8080:8080'
    command: python app.py

  tbot:
    build: .
    env_file:
      - .env
    container_name: 'shortener_bot'
    restart: always
    command: python bot.py

  mongo:
    image: mongo:6
    restart: always
    container_name: 'mongo'
    hostname: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin